# Generated by Django 5.2.8 on 2025-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequest',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of allergies'),
        ),
        migrations.AlterField(
            model_name='reciperequest',
            name='cuisine',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reciperequest',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of ingredients'),
        ),
    ]
